pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot\[bot\]$
      - check-success=run-test
      - check-success=auto-approve
    actions:
      merge:
        method: squash
