name: Build pages
on:
  pull_request:
    branches: [main]
jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.2
        with:
          node-version: "14.x"
      - run: npm ci && npm run build
