name: Build pages
on:
  pull_request:
    branches: [main]
jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
      - run: npm install --no-optional && npm run build
