name: Publish to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  release-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "14.x"
      - run: npm ci && npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: tianhaoz95
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "tianhaoz@umich.edu"
          git config --global user.name "tianhaoz95"
          npm run deploy
